version: '3.8'

services:
  php:
    image: fleothaud/fl-php-pdo:fpm-alpine3.18
    volumes:
      - ./www:/var/www/html
    environment:
      DB_HOST: mariadb
      DB_NAME: ${MARIADB_DB_NAME}
      DB_USER: ${MARIADB_DB_USER}
      DB_PASSWORD: ${MARIADB_DB_PASSWORD}

    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - php


  mariadb:
    image: mariadb:latest
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB_NAME}
      MARIADB_USER: ${MARIADB_DB_USER}
      MARIADB_PASSWORD: ${MARIADB_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
