version: '3.8'

services:
  php:
    image: fleothaud/fl-php-pdo:7.4-fpm-alpine
    volumes:
      - ./www:/var/www/html
    environment:
      DB_HOST: mysql
      DB_NAME: ${MYSQL_DB_NAME}
      DB_USER: ${MYSQL_DB_USER}
      DB_PASSWORD: ${MYSQL_DB_PASSWORD}

    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - php

  # mysql:
  #     image: mysql:5.7
  #     environment:
  #       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #       MYSQL_DATABASE: ${MYSQL_DB_NAME}  
  #       MYSQL_USER: ${MYSQL_DB_USER}
  #       MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
  #     volumes:
  #       - db_data:/var/lib/mysql
  #       - ./mysql/initdb:/docker-entrypoint-initdb.d
  #     networks:
  #       - backend

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
